#ifndef _ASDEFS_FLAGS
#define _ASDEFS_FLAGS
#define ASDEFS_FLAGS_SS	1
#define ASDEFS_FLAGS_SS2	2
#define ASDEFS_FLAGS_ATT	4
#define ASDEFS_FLAGS_DBG	8
#define ASDEFS_FLAGS_ROOT	16
#define ASDEFS_FLAGS_SEF	32
#define ASDEFS_FLAGS_HT	64
#define ASDEFS_FLAGS_MAL	128
#define ASDEFS_FLAGS_ATD	256
#define ASDEFS_FLAGS_GCT	512
#define ASDEFS_FLAGS_IAP	1024
#define ASDEFS_FLAGS_DEV	2048
#define ASDEFS_FLAGS_SYM_OBJC_CLASS	16384
#define ASDEFS_FLAGS_SYM_NATIVE	8192
#define ASDEFS_FLAGS_PROXY	1
#define ASDEFS_FLAGS_DYLDLIB	16384
#define ASDEFS_FLAGS_ENVEXIST	8192
#endif // _ASDEFS_FLAGS
