# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jni/config_parser/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jni/config_parser/config.proto',
  package='',
  serialized_pb=_b('\n\x1ejni/config_parser/config.proto\"0\n\x0bTestDisable\x12\x0e\n\x06testId\x18\x01 \x02(\r\x12\x11\n\tsubTestid\x18\x02 \x01(\r\"\x98\x01\n\x06\x43onfig\x12\x0f\n\x07license\x18\x01 \x02(\x0c\x12\x0b\n\x03\x61pp\x18\x02 \x02(\x0c\x12\x0b\n\x03org\x18\x03 \x01(\x0c\x12\x12\n\napp_signer\x18\x05 \x01(\x0c\x12\x15\n\rurl_bootstrap\x18\x08 \x01(\x0c\x12\x14\n\x0curl_messages\x18\t \x01(\x0c\x12\"\n\x0ctestDisables\x18\x10 \x03(\x0b\x32\x0c.TestDisable')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TESTDISABLE = _descriptor.Descriptor(
  name='TestDisable',
  full_name='TestDisable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='testId', full_name='TestDisable.testId', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subTestid', full_name='TestDisable.subTestid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=82,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='license', full_name='Config.license', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app', full_name='Config.app', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='org', full_name='Config.org', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_signer', full_name='Config.app_signer', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url_bootstrap', full_name='Config.url_bootstrap', index=4,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url_messages', full_name='Config.url_messages', index=5,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='testDisables', full_name='Config.testDisables', index=6,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=237,
)

_CONFIG.fields_by_name['testDisables'].message_type = _TESTDISABLE
DESCRIPTOR.message_types_by_name['TestDisable'] = _TESTDISABLE
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG

TestDisable = _reflection.GeneratedProtocolMessageType('TestDisable', (_message.Message,), dict(
  DESCRIPTOR = _TESTDISABLE,
  __module__ = 'jni.config_parser.config_pb2'
  # @@protoc_insertion_point(class_scope:TestDisable)
  ))
_sym_db.RegisterMessage(TestDisable)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(
  DESCRIPTOR = _CONFIG,
  __module__ = 'jni.config_parser.config_pb2'
  # @@protoc_insertion_point(class_scope:Config)
  ))
_sym_db.RegisterMessage(Config)


# @@protoc_insertion_point(module_scope)
